services:
  - type: web
    name: miniblog
    env: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails db:prepare && bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: miniblog-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_ENV
        value: production
      - key: RAILS_SERVE_STATIC_FILES
        value: true
      - key: RAILS_LOG_TO_STDOUT
        value: true
      - key: WEB_CONCURRENCY
        value: 1

databases:
  - name: miniblog-db
    databaseName: miniblog_production
    user: miniblog_user
    plan: free 